# Generated by Django 6.0.8 on 2026-08-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat/"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="messaging.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
