# Generated by Django 6.0.8 on 2026-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_payment_id",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
